In [1]:
import pandas as pd
from scipy.stats import chi2_contingency, ttest_ind

In [2]:

# Load your dataset
data = pd.read_csv('A:/10x/10Acadamay-Week3/Data_Ver/Insurance_Data.csv')

C:\Users\Admin\AppData\Local\Temp\ipykernel_12860\700483299.py:2: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('A:/10x/10Acadamay-Week3/Data_Ver/Insurance_Data.csv')

In [3]:
data.head()

,Unnamed: 0,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [4]:
data.columns

Index(['Unnamed: 0', 'UnderwrittenCoverID', 'PolicyID', 'TransactionMonth',
       'IsVATRegistered', 'Citizenship', 'LegalType', 'Title', 'Language',
       'Bank', 'AccountType', 'MaritalStatus', 'Gender', 'Country', 'Province',
       'PostalCode', 'MainCrestaZone', 'SubCrestaZone', 'ItemType', 'mmcode',
       'VehicleType', 'RegistrationYear', 'make', 'Model', 'Cylinders',
       'cubiccapacity', 'kilowatts', 'bodytype', 'NumberOfDoors',
       'VehicleIntroDate', 'CustomValueEstimate', 'AlarmImmobiliser',
       'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff',
       'Rebuilt', 'Converted', 'CrossBorder', 'NumberOfVehiclesInFleet',
       'SumInsured', 'TermFrequency', 'CalculatedPremiumPerTerm',
       'ExcessSelected', 'CoverCategory', 'CoverType', 'CoverGroup', 'Section',
       'Product', 'StatutoryClass', 'StatutoryRiskType', 'TotalPremium',
       'TotalClaims'],
      dtype='object')

In [6]:
# Get unique value counts for all columns
unique_value_counts = {col: data[col].nunique() for col in data.columns}

# Print the unique value counts for each column
for col, count in unique_value_counts.items():
    if(count>1 and count<=3):
        print(f"Column '{col}' : {count} ")

Column 'IsVATRegistered' : 2
Column 'AccountType' : 3
Column 'MaritalStatus' : 3
Column 'Gender' : 3
Column 'AlarmImmobiliser' : 2
Column 'TrackingDevice' : 2
Column 'NewVehicle' : 2
Column 'WrittenOff' : 2
Column 'Rebuilt' : 2
Column 'Converted' : 2
Column 'TermFrequency' : 2

In [7]:
# Select relevant columns for analysis
columns_of_interest = ['AlarmImmobiliser', 'Gender']

In [8]:
# Data Segmentation
group_a = data[data['AlarmImmobiliser'] == 'Yes']  
group_b = data[data['AlarmImmobiliser'] == 'No']

In [9]:
# Statistical Testing
for column in columns_of_interest:
    if data[column].dtype == 'object':
        # Categorical data - Chi-squared test
        contingency_table = pd.crosstab(data[column], data['Gender'])
        chi2, p, _, _ = chi2_contingency(contingency_table)
        print(f"Chi-squared test p-value for '{column}': {p}")
        
        # Analyze p-value to reject/nullify the null hypothesis
        
    else:
        # Numerical data - T-test
        t_stat, p = ttest_ind(group_a[column], group_b[column])
        print(f"T-test p-value for '{column}': {p}")

Chi-squared test p-value for 'AlarmImmobiliser': 0.0020673290443831566
Chi-squared test p-value for 'Gender': 0.0

In [10]:
column_pairs = {
    'Gender': 'AlarmImmobiliser',
    'TrackingDevice': 'NewVehicle'
}

for column, kpi_column in column_pairs.items():
    group = data.groupby(column)
    
    if data[column].dtype == 'object':
        # Categorical data - Chi-squared test
        contingency_table = pd.crosstab(data[column], data[kpi_column])
        chi2, p, _, _ = chi2_contingency(contingency_table)
        print(f"Chi-squared test p-value for '{column}' vs. '{kpi_column}': {p}")

        # Analyze p-value to reject/nullify the null hypothesis

    else:
        # Numerical data - T-test
        group_a = group.get_group('Male')  
        group_b = group.get_group('Female') 
        t_stat, p = ttest_ind(group_a[kpi_column], group_b[kpi_column])
        print(f"T-test p-value for '{column}' vs. '{kpi_column}': {p}")

Chi-squared test p-value for 'Gender' vs. 'AlarmImmobiliser': 0.0020673290443831566
Chi-squared test p-value for 'TrackingDevice' vs. 'NewVehicle': 2.005763073298375e-73

In [11]:
columns_info = {
    'IsVATRegistered': 2,
    'AccountType': 3,
    'MaritalStatus': 3,
    'Gender': 3,
    'AlarmImmobiliser': 2,
    'TrackingDevice': 2,
    'NewVehicle': 2,
    'WrittenOff': 2,
    'Rebuilt': 2,
    'Converted': 2,
    'TermFrequency': 2
}

In [24]:
column_pairs = [
    ('IsVATRegistered', 'AccountType'),
    ('IsVATRegistered', 'MaritalStatus'),
    ('IsVATRegistered', 'Gender'),
    ('AccountType', 'MaritalStatus'),
    ('AccountType', 'Gender'),
    ('MaritalStatus', 'Gender'),
    ('Gender', 'AlarmImmobiliser'),
    ('Gender', 'TrackingDevice'),
    ('Gender', 'NewVehicle'),
    ('Gender', 'WrittenOff'),
    ('Gender', 'Rebuilt'),
    ('Gender', 'Converted'),
    ('Gender', 'TermFrequency')
]

In [29]:

# Convert boolean columns to numerical type
boolean_cols = [    'IsVATRegistered',
    'AccountType',
    'MaritalStatus',
    'Gender',
    'AlarmImmobiliser',
    'TrackingDevice',
    'NewVehicle',
    'WrittenOff',
    'Rebuilt',
    'Converted',
    'TermFrequency']

data[boolean_cols] = data[boolean_cols].astype(str)

# Statistical Testing for all column pairs
for pair in column_pairs:
    col1, col2 = pair
    contingency_table = pd.crosstab(data[col1], data[col2])

    if all(data[col].dtype == 'object' for col in pair):
        # Categorical data - Chi-squared test
        chi2, p, _, _ = chi2_contingency(contingency_table)
        print(f"Chi-squared test p-value for '{col1}' vs. '{col2}': {p}")

        # Analyze p-value to reject/nullify the null hypothesis

    else:
        # Numerical data - T-test
        t_stat, p = ttest_ind(data[col1], data[col2])
        print(f"T-test p-value for '{col1}' vs. '{col2}': {p}")

Chi-squared test p-value for 'IsVATRegistered' vs. 'AccountType': 0.0
Chi-squared test p-value for 'IsVATRegistered' vs. 'MaritalStatus': 6.205086477915291e-07
Chi-squared test p-value for 'IsVATRegistered' vs. 'Gender': 6.743463113631323e-58
Chi-squared test p-value for 'AccountType' vs. 'MaritalStatus': 0.0
Chi-squared test p-value for 'AccountType' vs. 'Gender': 0.0
Chi-squared test p-value for 'MaritalStatus' vs. 'Gender': 0.0
Chi-squared test p-value for 'Gender' vs. 'AlarmImmobiliser': 0.0020673290443831566
Chi-squared test p-value for 'Gender' vs. 'TrackingDevice': 0.0
Chi-squared test p-value for 'Gender' vs. 'NewVehicle': 1.1985578507224207e-18
Chi-squared test p-value for 'Gender' vs. 'WrittenOff': 0.4341081732285642
Chi-squared test p-value for 'Gender' vs. 'Rebuilt': 0.4341081732285642
Chi-squared test p-value for 'Gender' vs. 'Converted': 0.10343446468117257
Chi-squared test p-value for 'Gender' vs. 'TermFrequency': 0.003831607200859411

### Chi-squared Test Results Interpretation:

#### Analysis of Relationships:
- The Chi-squared test results reveal the following significant relationships between the variables:

1. **'IsVATRegistered' vs. 'AccountType':**
   - The p-value of 0.0 indicates a significant relationship between 'IsVATRegistered' and 'AccountType'.

2. **'IsVATRegistered' vs. 'MaritalStatus':**
   - A p-value of 6.205086477915291e-07 suggests a significant relationship between 'IsVATRegistered' and 'MaritalStatus'.

3. **'IsVATRegistered' vs. 'Gender':**
   - The very low p-value of 6.743463113631323e-58 indicates a significant relationship between 'IsVATRegistered' and 'Gender'.

4. **'AccountType' vs. 'MaritalStatus':**
   - The p-value of 0.0 indicates a significant relationship between 'AccountType' and 'MaritalStatus'.

5. **'AccountType' vs. 'Gender':**
   - A p-value of 0.0 reveals a significant relationship between 'AccountType' and 'Gender'.

6. **'MaritalStatus' vs. 'Gender':**
   - The p-value of 0.0 indicates a significant relationship between 'MaritalStatus' and 'Gender'.

7. **'Gender' vs. 'AlarmImmobiliser', 'TrackingDevice', 'NewVehicle':**
   - Significant relationships are observed with p-values of 0.0020673290443831566, 0.0, and 1.1985578507224207e-18, respectively.

8. **'Gender' vs. 'WrittenOff', 'Rebuilt', 'Converted', 'TermFrequency':**
   - The p-values suggest no significant relationship between 'Gender' and these variables (p > 0.05).

#### Implications and Recommendations:
- These significant relationships offer valuable insights for decision-making.
- Further analysis and interpretation of these results within the context of the study are crucial for deriving meaningful conclusions.